### ISSUE TITLE
关于model的set和get，是否限制只有通过set设置的属性save的时候才生效

### ISSUE THREAD

**Issue by lyd600lty** [HackPlan/RootPanel#12]
例如：

```
user.attributes.name = 'foo' 
user.save()  //无效

user.set('name','foo')
user.save()  //有效
```

**Comment by jysperm** [comment]
为什么要叫 attributes 而不是叫 data.

然后我觉得 get 和 set 太繁琐了，完全可以去掉。

**Comment by jysperm** [comment]
create 是每个子类都必须重写的么？

**Comment by lyd600lty** [comment]
因为set可以接受对象，就可以一下修改多个数据，感觉这样规范些

**Comment by lyd600lty** [comment]
对啊，都得写啊，这是我能想到的办法了。栈爆上什么方法都没有，这样其实还挺好的吧。
还有一个就是table函数可以考虑选择性省略，不过需要规定集合的规范，默认的话就是User的类对应的collection是users，如果有需要的话可以重写

**Comment by jysperm** [comment]
还有，

文档放在 DOC 文件夹里，不用 Wiki.
Model 里面没必要搞重载什么的，这样注释什么的会简单一点。
Model 里不要抛异常，也就是说 Model 对传进来的数据是完全信任的。

**Comment by lyd600lty** [comment]
可是查数据库会有异常。。。

**Comment by jysperm** [comment]
查数据库不算， model本身不抛异常

**Comment by lyd600lty** [comment]
你的地盘你做主。。

**Comment by lyd600lty** [comment]
不过create得重写，因为要构建新的实例
