### ISSUE TITLE
需要对 RP3 的消息通知系统进行设计

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#18]
包括：
- 基于 WebSocket 的实时通知(似乎必要性存疑)
- 基于邮件的通知

**Comment by lyd600lty** [comment]
邮件是必要的，但是不是所有消息都要邮件，可以弄个socket

**Comment by shanhaoli** [comment]
考虑QQrobot没？

**Comment by jysperm** [comment]
@Suith27 有必要么？

**Comment by jysperm** [comment]
再说有个 JavaScript 写的 QQ 机器人实现，估计要比 C++ 写的用起来方便一点。
https://github.com/xhan/qqbot

**Comment by shanhaoli** [comment]
好吧。我没看通知，现在才回复-，-
不重要的信息可以由QQ送嘛。顺便还可以QQ查询，比如说[状态]、[Ping]等，可以直接回复。

**Comment by jysperm** [comment]
QQ 不开放 API, 维护起来多麻烦

**Comment by shanhaoli** [comment]
好吧╮(￣▽￣")╭
