### ISSUE TITLE
要不要考虑把所有的 user 更名为 account

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#19]

**Comment by lyd600lty** [comment]
还有login 和 signup不对应啊。。signin
在 2014年3月15日，下午4:49，精英王子 notifications@github.com 写道：

**Comment by lyd600lty** [comment]
随意啊，就一点，要改趁早
在 2014年3月15日，下午4:49，精英王子 notifications@github.com 写道：

**Comment by jysperm** [comment]
同时『用户』改成『帐号』

**Comment by lyd600lty** [comment]
好，晚上我把代码整理下
在 2014年3月15日，下午5:04，精英王子 notifications@github.com 写道：

**Comment by jysperm** [comment]
我来改
