### ISSUE TITLE
作为一个设计师牛的工作 @oranzhang

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#2]
- 给 Bootstrap3 配色：知乎蓝
- 调研前端要不要使用某种框架(我倾向于不要)
- UI 的草图

其他工作：
- 调研用户系统和工单系统应该实现哪些功能

**Comment by lyd600lty** [comment]
前端用不用框架看需求被，用的话推荐bb

**Comment by jysperm** [comment]
我倾向于不用，前端工作并不多，jQuery 就够了。

**Comment by krhougs** [comment]
#6 中的设计在BS中不难实现哟

**Comment by jysperm** [comment]
http://v3.bootcss.com/customize/

配色在这里配就行了。

**Comment by krhougs** [comment]
自己弄=-=

**Comment by jysperm** [comment]
你也没给配色的值啊

**Comment by krhougs** [comment]
图里有，明显你没有仔细看

------------------ Original ------------------
