### ISSUE TITLE
前端的构建工具配置

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#20]
用 gulp 还是直接用 make?

**Comment by lyd600lty** [comment]
gulp吧

**Comment by jysperm** [comment]
你写一下 gulp 的配置文件吧

**Comment by lyd600lty** [comment]
要不要lint 和 压缩

**Comment by jysperm** [comment]
先做最简单的，能编译就好

**Comment by lyd600lty** [comment]
现在都可以了啊，你试试，还支持实时的
在 2014年3月16日，下午3:58，精英王子 notifications@github.com 写道：

**Comment by jysperm** [comment]
无所谓，开发环境有 IDE, 这个构建工具主要是用于部署的。
其实我感觉还不如搞个 Makefile 呢，我去搞个 Makefile 的分支试试。

**Comment by lyd600lty** [comment]
也好，其实gulp真不错
