### ISSUE TITLE
用户使用手册(WIKI)模块

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#21]
目录在 /WIKI, 里面就是 .md 文件，以后会被显示在官网上。
不爱写代码了，可以来写写面向用户的使用手册。

原使用手册：
http://wiki.jysperm.me/rp:user_manual

**Comment by jysperm** [comment]
大家可以直接提交 FAQ, 教程，原理概述 等形式的 .md 文件。

**Comment by lyd600lty** [comment]
大家是指用户么？
在 2014年3月16日，上午9:14，精英王子 notifications@github.com 写道：

**Comment by jysperm** [comment]
是的
