### ISSUE TITLE
用 Node 重写原 RP 主机状态监视器

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#23]
这个工作交给 @faceair 

用 Coffee 写，支持 WebSocket 实时刷新数据。

原状态监视器：http://jp1.rpvhost.net/status/taskinfo.php

**Comment by lyd600lty** [comment]
这不是websocket吧。ajax请求就可以了

**Comment by jysperm** [comment]
当然要用 websocket 才行啊。

**Comment by lyd600lty** [comment]
难道是把定时器放到后端？

**Comment by lyd600lty** [comment]
我看青云就是10秒一请求的

**Comment by jysperm** [comment]
算是吧，这个可以考虑单独跑一个进程

**Comment by faceair** [comment]
打算后端用socke.io，咋样？

**Comment by faceair** [comment]
状态监视器要实现的功能：
- 服务器操作系统
- 服务器当前时间
- 服务器已运行时间
- CPU型号
- CPU使用状况
- 硬盘使用状况
- 内存使用状况(包括物理内存/Cache/真实内存/SWAP分区)
- 系统平均负载
- 用户进程状况
- 所有用户进程状况

差不多就是综合雅黑探针和上个版本的状态监视器，前端换用鞋拔子3.0和coffee

**Comment by lyd600lty** [comment]
socket可以啊，文档搞好～

**Comment by jysperm** [comment]
嗯，没什么问题

**Comment by lyd600lty** [comment]
@faceair 打算神马时候开工？～

**Comment by jysperm** [comment]
https://github.com/faceair/NodeMonitor

**Comment by faceair** [comment]
基本就是这个样子了，你们看看有啥要改的
