### ISSUE TITLE
参与成员介绍

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#3]
@jysperm RP2 作者，RP 主机维护者，RP3 牵头人。对前端 JS 了解较少，审美观畸形，除此之外可以完成其他所有工作。预定负责和 Linux 系统服务联系较为紧密的部分，即各『服务插件』。

@lyd600lty 主动参加，前后端 JS 都能写。不情愿写 UI 以及设计 UI.

@sxd1140 主动参加，可以写 Node, 对 Linux 系统服务不太了解。

@oranzhang 著名设计师，擅长前端，时间不多，被强拉来的。

@RicterZ Python 独立开发者，Web 安全牛，写过前端，初学 Node。被强拉来的，时间不多。

@faceair 

描述不准确大家可以补充。

**Comment by jysperm** [comment]
话说除了 @lyd600lty, 你们都跑到哪去了

**Comment by sxd1140** [comment]
不知道如何插手的小打杂飘过

**Comment by jysperm** [comment]
你能写什么啊

**Comment by sxd1140** [comment]
什么都不行 你安排一个 我试试

**Comment by lyd600lty** [comment]
设计最好先搞定，这样我写完model那些就可以去搞前端了

**Comment by jysperm** [comment]
看来就剩我们两个人了

**Comment by lyd600lty** [comment]
嗯，那就老样子，前端我来搞。

**Comment by sxd1140** [comment]
你们两个就够了 加油
