### ISSUE TITLE
准备加快进度，三月份之前完成雏形

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#4]
- 用户系统和工单系统大致完成
- 插件系统完成雏形，编写一个示例插件
- 可以部署到测试服务器

准备最近一周搞一台 VPS, 专用于测试。

**Comment by RicterZ** [comment]
是不是有点快啊...

**Comment by jysperm** [comment]
已经跳票很久了好吧，再说这只是雏形。

**Comment by lyd600lty** [comment]
我这还有几个linode。。

**Comment by RicterZ** [comment]
好吧..大概三月之后我才能投入开发..不过大概你们都写完了=-=

**Comment by jysperm** [comment]
准备搞个青云，便宜，方便，速度还快。

**Comment by jysperm** [comment]
@RicterZ 那你就找安全漏洞好了。

**Comment by RicterZ** [comment]
OK。
