### ISSUE TITLE
用户系统功能讨论稿

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#5]
## 功能

页面(3 个)：
- 注册
- 登录
- 主面板

登录后是一个主面板，类似 RP2 现在的面板。
左面是导航条，右面是主体区域，具体有什么内容要取决于插件，这部分我们在插件系统中再讨论。

登录后，顶部导航条会显示用户名，和提醒(其实就是工单)数量，这个和 RP2 现在的情况也是差不多的。
## 数据库

数据库中的每条用户数据大致是这样的。

首先基本信息：
- username
- email
- passwd
- passwd_salt
- signup_at

验证相关的信息：
- tokens[]
  - token
  - created_at
  - updated_at
  - available
  - attribute

插件化相关的信息：
- groups[]
- settings{}
- attribute{}

---

groups 即用户所属的组，这个组可以是管理员，或者付费用户，或者试用用户等等。

settings 主要是由用户输入的一些个性化信息，如联系方式，默认语言等。

attribute 是用户的一些其他属性，如是否启用了某个服务。
## 安全

密码散列算法会使用一个和 RP2 不兼容的算法：

```
sha256(sha256(passwd) + passwd_salt)
```

其中 passwd_salt 是一个 256 bit 的 Hex 随机数，这个算法是我前两天调研的，最简单也最安全的用户密码储存方案。

tokens.token 也是一个 256 bit 的Hex 随机数，tokens.available 记录了这个 Token 是否可用，tokens.attribute 里会储存一些额外信息，例如 IP 和 UA.

**Comment by jysperm** [comment]
默认首页会重定向到登录页，登录后重定向到面板。

至于像现在 RP 这样的介绍页会以插件实现。

**Comment by lyd600lty** [comment]
groups为什么是数组，用户只能属于一个组吧？

**Comment by jysperm** [comment]
用户可以同时属于多个组

**Comment by lyd600lty** [comment]
![2014-02-16 1 57 02](https://f.cloud.github.com/assets/2917899/2178505/99d5ad16-966a-11e3-92d2-1214d827b5d7.png)
user的结构，@jysperm 看看有没有问题

**Comment by jysperm** [comment]
signup_at 用 unix 时间戳吧

**Comment by jysperm** [comment]
要么就用 Date

**Comment by lyd600lty** [comment]
现在难道不是时间戳。。。
睡了

**Comment by jysperm** [comment]
现在这个是js的精确到毫秒的啊

**Comment by lyd600lty** [comment]
除以1000不就好了

**Comment by jysperm** [comment]
打算 signup_at 用 MongoDB 的 ISODate
