### ISSUE TITLE
需要制作的宣传页面

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#55]
- [x] / - 首页
- [x] /panel/pay/ - 支付页面，上面也会显示支付历史
- [x] /public/wiki/ - 用户手册(WIKI)
- [ ] /public/monitor/ - 服务器状态监视器(NodeMonitor)
- [x] /public/services/ - 介绍 RP 主机支持的各种服务

**Comment by krhougs** [comment]
动态数据部分的代码先push上吧  我周末弄

**Comment by jysperm** [comment]
这部分我来做就好了嘛，用 bootstrap.

**Comment by krhougs** [comment]
等六月份我把微电影忙完了就开始重写前端

**Comment by lyd600lty** [comment]
这是宣传页面？
