### ISSUE TITLE
主页部分设计初稿

### ISSUE THREAD

**Issue by krhougs** [HackPlan/RootPanel#6]
![-2-01](https://f.cloud.github.com/assets/1382065/2150703/f3484084-9403-11e3-9043-8b24bb448ad7.png)
![-2-02](https://f.cloud.github.com/assets/1382065/2150705/f525d59c-9403-11e3-98f2-a899db28905f.png)
![-2-03](https://f.cloud.github.com/assets/1382065/2150706/f7be13f0-9403-11e3-9c92-a587ab4255c3.png)
![-2-04](https://f.cloud.github.com/assets/1382065/2150708/fa27e044-9403-11e3-8927-0ee744544146.png)

如图所示

**Comment by jysperm** [comment]
这太复杂了吧，然后我倾向于注册和登录不使用弹出层。

**Comment by krhougs** [comment]
@jysperm  User Experience

**Comment by krhougs** [comment]
P.S. 没时间写CSS
