### ISSUE TITLE
工单系统功能初步讨论稿

### ISSUE THREAD

**Issue by jysperm** [HackPlan/RootPanel#7]
工单就是用户和管理员沟通的主要途径，相比于 RP2, RP3 计划实现这些功能：
- 管理员可以公开工单，作为类似 FAQ 的东西
- 可以合并多个工单，比如多个用户提出同一个问题时，管理员可以合并多个工单，以便统一汇报进度
- 工单支持 Markdown

RP2 的工单类型一直都是个摆设，我本来打算根据工单类型，会在工单页面上显示最常见的问题 FAQ 的。

和之前一样，在 RP3 里所有通知都体现为工单，顶部导航条的右边会显示当前开放中的工单数量。和之前一样，工单是有邮件提醒的。

工单的类型，也算是处理流程，和之前也差不多：
- 等待管理员回复
- 等待用户回复
- 管理员标记已完成
- 关闭

根据我使用 RP2 的体验，应该增加一个 15 天后自动关闭工单的功能。

**Comment by lyd600lty** [comment]
略显复杂。

**Comment by jysperm** [comment]
工单和回复都预留了 attribute 字段，到时候各种高端功能可以以插件实现。
