### ISSUE TITLE
安装过程有点复杂，能弄个脚本就好了

### ISSUE THREAD

**Issue by yanest** [HackPlan/RootPanel#86]

**Comment by jysperm** [comment]
安装步骤都写在 INSTALL.md 里了，考虑了很久之后还是决定不写安装脚本了。主要是考虑下面几个原因：

首先是不好选择用什么语言来写，我不是很懂 bash, 如果用 node 写的话，那还是要用户先配置好 node 环境，也没解决太多问题。
另一方面就是因为现在用户太少，测试也不够充分，安装过程中还是有很多需要用户考虑和处理错误的部分，可能还要考虑不同发行版和不同版本直接的兼容性，自动化脚本不是很好写。

不过以后还是有可能加上的。
