### ISSUE TITLE
vagrant  启动不起来啊，这是咋回事

### ISSUE THREAD

**Issue by yanest** [HackPlan/RootPanel#88]
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'jysperm/rootpanel' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'jysperm/rootpanel'
    default: URL: https://vagrantcloud.com/jysperm/rootpanel
A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '0.8.0-1'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.

**Comment by jysperm** [comment]
大概是我使用 Vagrant 的方法有问题，导致了两个问题：
1. `Vagrantfile` 中第 5 行需要改为 `config.vm.box = "jysperm/rootpanel"`, 这个修改目前还没更新到 master 上。
2.  Vagrant Cloud 上的版本号不符合 X.Y.Z 的要求，这个已经改了。

**Comment by jysperm** [comment]
已更新至 master
