### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by bjyuan** [HackPlan/RootPanel#89]
按照安装教程一步步来的，但服务没有启示起来。
运行下面的命令：
su rpadmin
node /home/rpadmin/RootPanel/start.js
提示：
/home/rpadmin/RootPanel/node_modules/mongodb/lib/mongodb/mongo_client.js:450
              throw err
                    ^
Error: EACCES, permission denied './core/template/ticket_create_email.html'
  at Object.fs.openSync (fs.js:438:18)
  at Object.fs.readFileSync (fs.js:289:15)
  at /home/rpadmin/RootPanel/app.coffee:57:31
  at /home/rpadmin/RootPanel/node_modules/mongodb/lib/mongodb/mongo_client.js:447:15
  at process._tickCallback (node.js:419:13)

看了一下，./core/template/ticket_create_email.html文件的权限没有问题。

然后，不知道问题出在哪里了……

**Comment by jysperm** [comment]
这确实是一个 Bug, 暂时你可以先 cd 到 `/home/rpadmin/RootPanel` 然后再 `node start.js`
