### ISSUE TITLE
RootPanel是否默认提供了Admin账户？

### ISSUE THREAD

**Issue by mk7024** [HackPlan/RootPanel#97]
今天折腾了一下RootPanel
但是装完后却不知道如何将账号提高为管理员级别.
请问RootPanel是否默认提供了一个管理员账号呢?

**Comment by minmemory** [comment]
默认是有的，怎么添加的话，我稍后回复你

---

该邮件由iPhone发送

------------------ Original ------------------

**Comment by jysperm** [comment]
不会自动生成管理员帐号，需要注册一个帐号后，在 MongoDB 把 groups 属性设置成 `['root']`

**Comment by caizixian** [comment]
Close it.
